/* Amendola Studios — bilingual copy and data.
   Every user-facing string lives here. Keys in `ui` map to data-i18n attributes in index.html. */

window.AS_CONTENT = {
  ui: {
    it: {
      metaTitle: 'Amendola Studios · App iOS, web e intelligenza artificiale',
      metaDesc: 'Studio di sviluppo software a Napoli. App iOS, web e AI: dall’idea allo store, e poi di nuovo da capo.',
      skip: 'Vai al contenuto',
      navLabel: 'Principale',
      home: 'Amendola Studios, torna su',
      navApps: 'App', navServices: 'Servizi', navBook: 'Libro', navStudio: 'Studio', navWrite: 'Scrivimi',
      langLabel: 'Lingua', menu: 'Menu',
      logoAlt: 'Il simbolo infinito di Amendola Studios',
      h1a: 'Progettiamo app', h1b: 'che restano.',
      heroSub: 'iOS, web e intelligenza artificiale. Dall’idea allo store, e poi di nuovo da capo: ogni release apre il giro successivo.',
      heroCta: 'Guarda le app', heroCta2: 'Raccontami un’idea',
      heroProof: 'Otto app pubblicate\nsull’App Store',
      appsH: 'Otto app, tutte sull’App Store.',
      appsP: 'Progettate, sviluppate e pubblicate in casa. Scegline una per vederla da vicino.',
      openStore: 'Apri su App Store', shotOf: 'Schermata di ',
      svcH: 'Cosa facciamo.',
      svcP: 'Chi disegna l’interfaccia scrive anche il codice. Niente passaggi di consegne, niente pezzi persi per strada.',
      loopH: 'Un ciclo,\nnon una linea.',
      loopP: 'Ogni prodotto percorre l’infinito. Si ascolta, si costruisce, si lancia, si misura. Poi si riparte da un punto più alto.',
      phase: 'Fase', of: 'di',
      labH: 'Ricerca, prototipi e università.',
      labP: 'Il laboratorio dietro le app: AI per la medicina, memoria per assistenti, sistemi distribuiti. I progetti d’esame hanno preso tutti 30/30.',
      bookKicker: 'Il libro',
      bookSub: 'Dai bit all’intelligenza artificiale: idee, mestieri e tecnologie che cambiano il mondo.',
      bookP: 'Un viaggio accessibile ma rigoroso, dai primi strumenti di calcolo ai computer quantistici. Bit, logica, grafi, crittografia e AI, con formule spiegate passo dopo passo ed esempi presi dalla medicina, dalla musica, dai trasporti. E tutti i mestieri dell’informatica oltre la programmazione.',
      bookPagesL: 'Pagine', bookDateL: 'Uscita', bookDate: 'luglio 2026', bookLangL: 'Lingua', bookLang: 'Italiano',
      bookCta: 'Acquista su Amazon',
      bookMore: 'Uno dei libri di divulgazione informatica scritti da Pierfrancesco, disponibili online.',
      bookAlt: 'Copertina del libro Cos’è davvero l’informatica di Pierfrancesco Amendola',
      photosLabel: 'Foto di Pierfrancesco', photo: 'Foto',
      role: 'Fondatore. Sviluppatore, ricercatore, autore.',
      prevPhoto: 'Foto precedente', nextPhoto: 'Foto successiva',
      aboutH: 'Codice, ricerca e un pianoforte. Lo stesso esercizio, ripetuto ogni giorno.',
      aboutP: 'Mi sono laureato in Informatica alla Federico II di Napoli nel 2026. Lavoro su sistemi di AI per l’analisi di immagini mediche, scrivo libri di divulgazione informatica e ho pubblicato otto app, ognuna costruita da solo, dalla prima bozza alla review di Apple. Amendola Studios nasce per mettere questo metodo al servizio di chi ha un’idea e vuole vederla funzionare.',
      gradLine: 'anni alla laurea. Il primo nella storia del corso di Informatica della Federico II a laurearsi prima dei 21.',
      pathH: 'Il percorso', pathHint: 'Scorri lateralmente',
      contactH: 'Hai un’idea?\nFacciamola girare.',
      fName: 'Nome', fEmail: 'Email', fProject: 'Il progetto',
      fPlaceholder: 'Cosa vuoi costruire, entro quando, con quale budget indicativo.',
      fSend: 'Invia',
      fMissing: 'Compila nome, email e progetto.',
      fBadEmail: 'Controlla l’indirizzo email.',
      mailSubject: 'Nuovo progetto da',
      sentH: 'Quasi fatto.',
      sentP: 'Si è aperta la tua app di posta con il messaggio pronto: premi invia e ti rispondo presto.',
      sentAgain: 'Scrivi un altro messaggio',
      footer: '© 2026 Amendola Studios · Napoli',
      backTop: 'Torna su'
    },
    en: {
      metaTitle: 'Amendola Studios · iOS apps, web and artificial intelligence',
      metaDesc: 'Software development studio in Naples, Italy. iOS, web and AI: from idea to App Store, then round again.',
      skip: 'Skip to content',
      navLabel: 'Main',
      home: 'Amendola Studios, back to top',
      navApps: 'Apps', navServices: 'Services', navBook: 'Book', navStudio: 'Studio', navWrite: 'Get in touch',
      langLabel: 'Language', menu: 'Menu',
      logoAlt: 'The Amendola Studios infinity mark',
      h1a: 'We build apps', h1b: 'that last.',
      heroSub: 'iOS, web and artificial intelligence. From idea to App Store, then round again: every release opens the next loop.',
      heroCta: 'See the apps', heroCta2: 'Tell me your idea',
      heroProof: 'Eight apps live\non the App Store',
      appsH: 'Eight apps, all on the App Store.',
      appsP: 'Designed, built and shipped in house. Pick one to take a closer look.',
      openStore: 'Open on the App Store', shotOf: 'Screenshot of ',
      svcH: 'What we do.',
      svcP: 'The person who designs the interface also writes the code. No handoffs, nothing lost along the way.',
      loopH: 'A loop,\nnot a line.',
      loopP: 'Every product travels the infinity loop. Listen, build, launch, measure. Then start again from higher ground.',
      phase: 'Phase', of: 'of',
      labH: 'Research, prototypes and university.',
      labP: 'The lab behind the apps: AI for medicine, memory for assistants, distributed systems. Every exam project scored 30/30, the top Italian grade.',
      bookKicker: 'The book',
      bookSub: 'From bits to artificial intelligence: the ideas, careers and technologies changing the world.',
      bookP: 'An accessible yet rigorous journey from the first calculating tools to quantum computers. Bits, logic, graphs, cryptography and AI, with formulas explained step by step and examples from medicine, music and transport. Plus every computing career beyond programming.',
      bookPagesL: 'Pages', bookDateL: 'Published', bookDate: 'July 2026', bookLangL: 'Language', bookLang: 'Italian',
      bookCta: 'Buy on Amazon',
      bookMore: 'One of the computer science books Pierfrancesco has written, available online.',
      bookAlt: 'Cover of the book Cos’è davvero l’informatica by Pierfrancesco Amendola',
      photosLabel: 'Photos of Pierfrancesco', photo: 'Photo',
      role: 'Founder. Developer, researcher, author.',
      prevPhoto: 'Previous photo', nextPhoto: 'Next photo',
      aboutH: 'Code, research and a piano. The same practice, repeated every day.',
      aboutP: 'I graduated in Computer Science from the University of Naples Federico II in 2026. I work on AI systems for medical image analysis, write popular computer science books and have shipped eight apps, each built solo from first sketch to Apple review. Amendola Studios exists to put that method to work for anyone with an idea they want to see running.',
      gradLine: 'years old at graduation. The first in the history of Federico II’s Computer Science programme to graduate before turning 21.',
      pathH: 'The journey', pathHint: 'Scroll sideways',
      contactH: 'Got an idea?\nLet’s get it running.',
      fName: 'Name', fEmail: 'Email', fProject: 'Your project',
      fPlaceholder: 'What you want to build, by when, and a rough budget.',
      fSend: 'Send',
      fMissing: 'Please fill in name, email and project.',
      fBadEmail: 'Please check the email address.',
      mailSubject: 'New project from',
      sentH: 'Almost there.',
      sentP: 'Your mail app opened with the message ready: hit send and I’ll reply soon.',
      sentAgain: 'Send another message',
      footer: '© 2026 Amendola Studios · Naples, Italy',
      backTop: 'Back to top'
    }
  },

  apps: [
    { name: 'AlcolSafe', slug: 'alcolsafe', year: '2026', url: 'https://apps.apple.com/it/app/alcolsafe/id6769685974?l=en-GB',
      cat: { it: 'Utility', en: 'Utilities' },
      desc: { it: 'Stima del tasso alcolemico e test di reattività fatti sul telefono, per capire con onestà se sei in condizione di guidare.', en: 'Blood alcohol estimates and reaction tests on your phone, for an honest answer on whether you are fit to drive.' } },
    { name: 'Linkly QR', slug: 'linkly', year: '2026', url: 'https://apps.apple.com/it/app/linkly-qr/id6771731975?l=en-GB',
      cat: { it: 'Utility', en: 'Utilities' },
      desc: { it: 'Crea e scansiona codici QR per link, Wi-Fi, contatti ed email. Funziona offline, senza tracciamento.', en: 'Create and scan QR codes for links, Wi-Fi, contacts and email. Works offline, no tracking.' } },
    { name: 'Specula', slug: 'specula', year: '2026', url: 'https://apps.apple.com/it/app/specula/id6777223253?l=en-GB',
      cat: { it: 'Grafica', en: 'Graphics & Design' },
      desc: { it: 'Estrae la palette da qualsiasi foto: colori dominanti, vivaci e tenui, pronti da salvare e condividere.', en: 'Pulls a palette from any photo: dominant, vibrant and muted colours, ready to save and share.' } },
    { name: 'UniStudy Italia', slug: 'unistudy', year: '2026', url: 'https://apps.apple.com/it/app/unistudy-italia/id6757367573?l=en-GB',
      cat: { it: 'Istruzione', en: 'Education' },
      desc: { it: 'Aule studio e biblioteche di oltre 100 atenei italiani, filtrabili per regione. Trovi il posto giusto in pochi secondi.', en: 'Study rooms and libraries across 100+ Italian universities, filtered by region. Find the right seat in seconds.' } },
    { name: 'SubTracker', slug: 'subtracker', year: '2026', url: 'https://apps.apple.com/it/app/subtracker-submanager/id6757951413?l=en-GB',
      cat: { it: 'Finanza', en: 'Finance' },
      desc: { it: 'Tutti gli abbonamenti in un posto: totale mensile e annuale, calendario dei rinnovi, statistiche chiare.', en: 'Every subscription in one place: monthly and yearly totals, a renewal calendar, clear stats.' } },
    { name: 'UniStats', slug: 'unistats', year: '2026', url: 'https://apps.apple.com/it/app/unistats/id6756898737?l=en-GB',
      cat: { it: 'Istruzione', en: 'Education' },
      desc: { it: 'Media ponderata, base di laurea e simulatore del voto finale. Gli esami si importano dal libretto in PDF.', en: 'Weighted average, graduation baseline and a final grade simulator for Italian students. Import exams straight from the PDF transcript.' } },
    { name: 'FreshCheck', slug: 'freshcheck', year: '2026', url: 'https://apps.apple.com/it/app/freshcheck/id6757205025?l=en-GB',
      cat: { it: 'Cibo', en: 'Food & Drink' },
      desc: { it: 'Dispensa e frigo sotto controllo, con scanner del codice a barre e avvisi prima della scadenza. Dati solo sul dispositivo.', en: 'Pantry and fridge under control, with a barcode scanner and alerts before things expire. Data stays on device.' } },
    { name: 'Ripassa!', slug: 'ripassa', year: '2025', url: 'https://apps.apple.com/it/app/ripassa-flashcard-minimal/id6756633023?l=en-GB',
      cat: { it: 'Istruzione', en: 'Education' },
      desc: { it: 'Flashcard essenziali con cinque modalità di studio, punti esperienza e statistiche. Tutto offline.', en: 'Minimal flashcards with five study modes, XP and stats. Fully offline.' } }
  ],

  services: [
    { title: { it: 'App iOS native', en: 'Native iOS apps' },
      text: { it: 'Dal concept alla pubblicazione sull’App Store: interfacce fluide, dati in locale, acquisti in-app e notifiche. Il territorio dove sono nate tutte le nostre app.', en: 'From concept to App Store release: fluid interfaces, on-device data, in-app purchases and notifications. Home turf for every app we have shipped.' },
      stack: 'Swift · SwiftUI · SwiftData · StoreKit 2 · Swift Charts' },
    { title: { it: 'iOS e Android insieme', en: 'iOS and Android together' },
      text: { it: 'Un solo codice per due piattaforme, senza rinunciare alla cura dei dettagli. Ideale per lanciare in fretta e misurare.', en: 'One codebase for two platforms, without cutting corners on detail. Ideal for launching fast and learning.' },
      stack: 'React Native · Expo · TypeScript · Flutter' },
    { title: { it: 'Web e backend', en: 'Web and backend' },
      text: { it: 'Siti, web app e servizi che reggono il carico: API sicure, autenticazione, database solidi, deploy containerizzato.', en: 'Sites, web apps and services that hold up under load: secure APIs, authentication, solid databases, containerised deploys.' },
      stack: 'TypeScript · Spring Boot · PostgreSQL · Supabase · Docker' },
    { title: { it: 'Intelligenza artificiale', en: 'Artificial intelligence' },
      text: { it: 'Modelli di deep learning, assistenti con memoria e analisi di immagini mediche. Ricerca vera, portata dentro prodotti usabili.', en: 'Deep learning models, assistants with memory and medical image analysis. Real research, shipped inside usable products.' },
      stack: 'Python · Deep Learning · GenAI · MCP' }
  ],

  /* x, y are positions on the 600×300 loop drawing. */
  steps: [
    { x: 404, y: 86, title: { it: 'Ascolto', en: 'Listen' }, text: { it: 'Capire persone, obiettivi e vincoli prima di scrivere una riga. Ogni progetto parte da una domanda precisa.', en: 'Understand people, goals and constraints before writing a line. Every project starts from a precise question.' } },
    { x: 470, y: 150, title: { it: 'Strategia', en: 'Strategy' }, text: { it: 'Scegliere piattaforme, stack e priorità. Un piano corto, con tappe che si possono misurare.', en: 'Choose platforms, stack and priorities. A short plan with milestones you can measure.' } },
    { x: 404, y: 214, title: { it: 'Design', en: 'Design' }, text: { it: 'Interfacce native ed essenziali, prototipi provati con persone vere prima dello sviluppo.', en: 'Native, essential interfaces, with prototypes tested on real people before development.' } },
    { x: 196, y: 86, title: { it: 'Sviluppo', en: 'Build' }, text: { it: 'Codice pulito e testato. Release frequenti, avanzamento sempre visibile.', en: 'Clean, tested code. Frequent releases, progress always visible.' } },
    { x: 130, y: 150, title: { it: 'Lancio', en: 'Launch' }, text: { it: 'Pubblicazione su App Store, Google Play o web, con pagine di supporto e privacy già pronte.', en: 'Release on the App Store, Google Play or the web, with support and privacy pages ready.' } },
    { x: 196, y: 214, title: { it: 'Evoluzione', en: 'Evolve' }, text: { it: 'Dati, recensioni, nuove versioni. Il ciclo ricomincia e il prodotto migliora a ogni giro.', en: 'Data, reviews, new versions. The loop starts again and the product improves every lap.' } }
  ],

  lab: [
    { name: { it: 'AI per imaging medico', en: 'AI for medical imaging' }, kind: { it: 'Ricerca, CNR', en: 'Research, CNR' }, stack: { it: 'Python, Deep Learning', en: 'Python, Deep Learning' }, year: '2025',
      desc: { it: 'Modelli di deep learning per l’analisi di immagini ecografiche, nati durante il tirocinio in bioinformatica al CNR. Lo stesso ambito ha vinto la Google Challenge Campania 2026, categoria Salute.', en: 'Deep learning models for ultrasound image analysis, started during a bioinformatics internship at Italy’s National Research Council (CNR). The same field won the Google Challenge Campania 2026, Health category.' } },
    { name: { it: 'Universal AI Brain', en: 'Universal AI Brain' }, kind: { it: 'Prototipo', en: 'Prototype' }, stack: { it: 'Python, MCP, Graph', en: 'Python, MCP, Graph' }, year: '2026',
      desc: { it: 'Un knowledge graph che collega progetti, decisioni e conversazioni, interrogabile da più assistenti AI attraverso MCP. Una memoria che non si azzera a ogni chat.', en: 'A knowledge graph linking projects, decisions and conversations, queryable by several AI assistants over MCP. Memory that does not reset with every chat.' } },
    { name: { it: 'JARVIS', en: 'JARVIS' }, kind: { it: 'Prototipo', en: 'Prototype' }, stack: { it: 'Python, LLM, Voce', en: 'Python, LLM, Voice' }, year: '2026',
      desc: { it: 'Assistente vocale in tempo reale collegato alla memoria del Universal AI Brain, per conversazioni che riprendono da dove si erano fermate.', en: 'A real-time voice assistant wired to the Universal AI Brain, so conversations pick up where they left off.' } },
    { name: { it: 'FedericoII App', en: 'FedericoII App' }, kind: { it: 'App, in arrivo', en: 'App, coming soon' }, stack: { it: 'React Native, TypeScript', en: 'React Native, TypeScript' }, year: '2026',
      desc: { it: 'Orari delle lezioni, aule e informazioni di campus in un’unica app per gli studenti della Federico II.', en: 'Timetables, classrooms and campus info in one app for Federico II students.' } },
    { name: { it: 'Battaglia navale multiplayer', en: 'Multiplayer Battleship' }, kind: { it: 'Università, 30/30', en: 'University, 30/30' }, stack: { it: 'C, Python, Docker', en: 'C, Python, Docker' }, year: '2025',
      desc: { it: 'Applicazione client-server con protocollo TCP progettato da zero, concorrenza con thread POSIX e deploy in container.', en: 'Client-server application with a TCP protocol designed from scratch, POSIX thread concurrency and containerised deployment.' } },
    { name: { it: 'Post Management System', en: 'Post Management System' }, kind: { it: 'Università, 30/30', en: 'University, 30/30' }, stack: { it: 'Java, Spring Boot', en: 'Java, Spring Boot' }, year: '2025',
      desc: { it: 'Piattaforma a microservizi con autenticazione JWT, persistenza su PostgreSQL e orchestrazione Docker.', en: 'Microservice platform with JWT authentication, PostgreSQL persistence and Docker orchestration.' } },
    { name: { it: 'FoodLab', en: 'FoodLab' }, kind: { it: 'Università, 30/30', en: 'University, 30/30' }, stack: { it: 'Java, Swing, SQL', en: 'Java, Swing, SQL' }, year: '2024',
      desc: { it: 'Gestionale desktop per corsi di cucina, con pattern DAO e database PostgreSQL.', en: 'Desktop management system for cooking courses, built on the DAO pattern and PostgreSQL.' } },
    { name: { it: 'SetVec', en: 'SetVec' }, kind: { it: 'Università, 30/30', en: 'University, 30/30' }, stack: { it: 'C++', en: 'C++' }, year: '2024',
      desc: { it: 'Struttura dati ordinata generica su vettore circolare, con ricerca binaria e attenzione alla complessità.', en: 'Generic ordered data structure on a circular vector, with binary search and care for complexity.' } }
  ],

  photos: [
    { src: 'assets/photos/smoking.jpg', pos: 'center 38%', cap: { it: 'Fuori dallo schermo', en: 'Away from the screen' }, alt: { it: 'Pierfrancesco in smoking su una terrazza al tramonto', en: 'Pierfrancesco in a tuxedo on a terrace at sunset' } },
    { src: 'assets/photos/podio.jpg', pos: 'center 28%', cap: { it: 'Federico II, intervento in aula', en: 'Federico II, speaking at the podium' }, alt: { it: 'Pierfrancesco parla al podio dell’Università Federico II', en: 'Pierfrancesco speaking at a University of Naples Federico II podium' } },
    { src: 'assets/photos/google-challenge.jpg', pos: '30% 45%', cap: { it: 'Google Challenge, presentazione', en: 'Google Challenge, presenting' }, alt: { it: 'Pierfrancesco presenta la Google Challenge davanti agli studenti', en: 'Pierfrancesco presenting the Google Challenge to a room of students' } },
    { src: 'assets/photos/team.jpg', pos: '42% 50%', cap: { it: 'Google Challenge Campania 2026, categoria Salute', en: 'Google Challenge Campania 2026, Health category' }, alt: { it: 'Il team premiato alla Google Challenge Campania con l’attestato', en: 'The winning team at Google Challenge Campania holding the certificate' } },
    { src: 'assets/photos/laurea.jpg', pos: 'center 22%', cap: { it: 'Laurea a 20 anni, 2026', en: 'Graduating at 20, 2026' }, alt: { it: 'Pierfrancesco con la corona d’alloro, la tesi e un mazzo di rose', en: 'Pierfrancesco wearing a laurel wreath, holding his thesis and roses' } }
  ],

  facts: [
    { k: { it: 'Codice', en: 'Code' }, v: { it: 'Swift, TypeScript, Python, Java. SwiftUI, React Native, Spring Boot.', en: 'Swift, TypeScript, Python, Java. SwiftUI, React Native, Spring Boot.' } },
    { k: { it: 'Certificazioni', en: 'Certifications' }, v: { it: 'Yale University, NVIDIA Deep Learning, Google AI, Cisco, Apple Search Ads.', en: 'Yale University, NVIDIA Deep Learning, Google AI, Cisco, Apple Search Ads.' } },
    { k: { it: 'Lingue', en: 'Languages' }, v: { it: 'Italiano, inglese e spagnolo da madrelingua. Francese e tedesco.', en: 'Native Italian, English and Spanish. French and German.' } },
    { k: { it: 'Fuori dallo schermo', en: 'Away from the screen' }, v: { it: 'Pianista dai 3 anni, autore di libri di informatica e per bambini, attore di teatro.', en: 'Pianist since age 3, author of computer science and children’s books, stage actor.' } }
  ],

  timeline: [
    { year: '2019', title: { it: 'Giornalista a 14 anni', en: 'Journalist at 14' }, text: { it: 'Articoli per Informazione Oggi. Prima lezione: scrivere chiaro.', en: 'Writing for Informazione Oggi. First lesson: write clearly.' } },
    { year: '2022', title: { it: 'Un centro per ragazzi', en: 'A youth centre' }, text: { it: 'Fonda e coordina un centro giovanile, fino al 2025.', en: 'Founds and runs a local youth centre until 2025.' } },
    { year: '2023', title: { it: 'Informatica, Federico II', en: 'Computer Science, Federico II' }, text: { it: 'Inizia la triennale a Napoli. Certificazione di inglese C2.', en: 'Starts his degree in Naples. C2 English certification.' } },
    { year: '2025', title: { it: 'CNR e prima app', en: 'CNR and a first app' }, text: { it: 'Tirocinio in bioinformatica. A dicembre Ripassa! arriva sull’App Store.', en: 'Bioinformatics internship. In December, Ripassa! lands on the App Store.' } },
    { year: '2026', title: { it: 'Google Challenge Campania', en: 'Google Challenge Campania' }, text: { it: 'Vince nella categoria Salute. Certificazione NVIDIA Deep Learning.', en: 'Wins the Health category. NVIDIA Deep Learning certification.' } },
    { year: '2026', title: { it: 'Certificazione Yale University', en: 'Yale University certification' }, text: { it: 'Corso “Introduction to Breast Cancer”.', en: '“Introduction to Breast Cancer” course.' } },
    { year: '2026', title: { it: 'Un libro sull’informatica', en: 'A book on computing' }, text: { it: 'A luglio esce “Cos’è davvero l’informatica”.', en: 'In July, “Cos’è davvero l’informatica” is published.' } },
    { year: '2026', title: { it: 'Laurea a 20 anni', en: 'Graduates at 20' }, text: { it: 'Il primo nella storia del corso di Informatica della Federico II a laurearsi prima dei 21.', en: 'The first in the history of Federico II’s Computer Science programme to graduate before 21.' } },
    { year: '2026', title: { it: 'Nasce Amendola Studios', en: 'Amendola Studios is born' }, text: { it: 'Otto app pubblicate. Il giro ricomincia, più ampio.', en: 'Eight apps live. The loop starts again, wider.' } }
  ]
};
